### PR TITLE
fix(core): treat OpenAPI validation failures as warnings instead of errors

### LINKED ISSUE #3072: Core: Validation throws error when using fastapi.sse
### Description

I am trying to use the new SSE function in the latest version of FastAPI, the fastapi.sse will attach `itemSchema` field in the generated openapi endpoint definition like this:
```
{
  "openapi": "3.1.0",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/api/events/": {
      "post": {
        "tags": [
          "stream"
        ],
        "summary": "Sse Endpoint",
        "operationId": "sse_endpoint",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "text/event-stream": {
                "itemSchema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string"
                    },
                    "event": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "retry": {
                      "type": "integer",
                      "minimum": 0
                    }
                  }
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "text/event-stream": {
                "schema": {
                  "$ref": "#/components/schemas/ErrorResponseSchema"
                }
              }
            }
          },
          "401": {
...
```

And when the `itemSchema` appear, the orval will throw an error like this:
```
api - Validation failed
Cause: [
{
  "message": "if must match \"else\" schema",
  "path": "/paths/~1api~1events~1"
},                                                    
...                                                     
```

And I have to manually exclude the sse endpoints in the fastapi app to make orval normally generate other schemas. I have already excluded sse endpoints in the orval config.

### Configuration (orval.config)

```ts
import { defineConfig, type InputOptions, type OperationOptions } from "orval";

const operationSpecificConfig: Record<string, OperationOptions> = {
  fetch_models: {
    query: {
      useInfinite: false,
      useSuspenseInfiniteQuery: false,
    },
  },
};

const input: InputOptions = {
  target: "../openapi.json",
  filters: {
    mode: "exclude",
    tags: ["stream"],
  },
};

export default defineConfig({
  api: {
    input,
    output: {
      clean: true,
      target: "./src/api/generated/endpoints/",
      schemas: "./src/api/generated/schemas/",
      operationSchemas: "./src/api/generated/schemas/params/",
      client: "react-query",
      mode: "tags-split",
      namingConvention: "kebab-case",
      override: {
        useTypeOverInterfaces: true,
        fetch: {
          includeHttpResponseReturnType: false,
        },
        mutator: {
          path: "./src/api/orval-mutator/custom-fetch.ts",
          name: "fetchApi",
        },
        query: {
          version: 5,
          useQuery: true,
          useInfinite: true,
          useMutation: true,
          useSuspenseQuery: true,
          useSuspenseInfiniteQuery: true,
          useInfiniteQueryParam: "page",
        },

        operations: operationSpecificConfig,
      },
    },
    hooks: {
      afterAllFilesWrite: ["biome format --write --config-path config/biome.format.jsonc"],
    },
  },
});
```

### Environment

  System:
    OS: Windows 11 10.0.26200
    CPU: (16) x64 AMD Ryzen 7 6800HS Creator Edition
    Memory: 2.15 GB / 13.69 GB

### Expected behavior

Orval just ignore the sse endpoints and normally resolve others.

### Actual behavior

Orval immediately throws error and exit.

### OpenAPI document (minimal, if applicable)

```json
{
  "openapi": "3.1.0",
  "info": {
    "title": "FastAPI",
    "version": "0.1.0"
  },
  "paths": {
    "/api/events/": {
      "post": {
        "tags": [
          "stream"
        ],
        "summary": "Sse Endpoint",
        "operationId": "sse_endpoint",
        "responses": {
          "200": {
            "description": "Successful Response",
            "content": {
              "text/event-stream": {
                "itemSchema": {
                  "type": "object",
                  "properties": {
                    "data": {
                      "type": "string"
                    },
                    "event": {
                      "type": "string"
                    },
                    "id": {
                      "type": "string"
                    },
                    "retry": {
                      "type": "integer",
                      "minimum": 0
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zeriong**
## Summary
- Change OpenAPI spec validation from hard error to warning, allowing code generation to proceed with non-standard fields (#3072)
- Add `input.validation` option (`boolean`, default `true`) to let users disable validation entirely
- Apply to both main spec validation (`import-specs.ts`) and transformer validation (`import-open-api.ts`)

## Problem
FastAPI SSE endpoints add a non-standard `itemSchema` field to response content. The `@scalar/openapi-parser` validator rejects this field, causing orval to throw and exit immediately. This blocks generation of all endpoints, even when the SSE endpoints are excluded via `input.filters`.

## Solution
Replace `throw new Error('Validation failed')` with `logWarning()` in both vlidation sites. When validation fails, orval now:
1. Prints a yellow warning with the validation errors
2. Suggests `input.validation: false` as an escape hatch
3. Continues with code generation

Users who want to completely skip validation can set:
```ts
input: {
  target: './openapi.json',
  validation: false,
}


<!-- This is an auto-generated comment: release notes by coderabbit.ai -->
## Summary by CodeRabbit

* **New Features**
  * Added an optional input setting to enable/disable OpenAPI validation (enabled by default).
  * Import flow now emits warnings with validation details for invalid specs instead of aborting the import.

* **Tests**
  * Added tests covering import behavior with validation enabled and disabled.

* **Chores**
  * Added an Angular Query generate script and introduced the Angular Query experimental dependency in samples/tests.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

### CODE REVIEW

File: packages/core/src/types.ts [hunk 1]
```diff
@@ -206,6 +206,7 @@ export interface NormalizedOperationOptions {
 export interface NormalizedInputOptions {
   target: string | OpenApiDocument;
   override: OverrideInput;
+  validation?: boolean;
```
Comment (melloware) [inline packages/core/src/types.ts]: I think we need docs for this setting?  @snebjorn any disagreement with this i think you removed validation previously?

**Review by melloware — CHANGES_REQUESTED** [review]

File: packages/core/src/types.ts (hunk 1 above)
Comment (zeriong) [reply packages/core/src/types.ts]: Good point about the docs — I'll add documentation for the `input.validation` setting.

I also noticed that `validateComponentKeys()` was running unconditionally even when `validation: false`. I've moved it inside the `if (validation)` block so the escape hatch works completely.

Additionally:

- Made `NormalizedInputOptions.validation` non-optional (since `normalizeOptions()` always assigns it)
- Removed the redundant `?? true` fallback in `importSpecs`

Regarding previous validation removal — this PR doesn't remove validation. It just downgrades failures from hard errors to warnings, with an opt-out for specs that have non-standard extensions like FastAPI's `itemSchema`. Default behavior still validates.

Comment (snebjorn) [reply packages/core/src/types.ts]: The reason for removing the option to disable validation was basically that we can't reasonably parse the OAS if it's invalid.
Sure it works sometimes but that's, lets call it, an undocumented feature. And it might break in minor updates.

If the option is called `unsafeDisableValidationYolo` and prints a VERY noticeable warning that says that no bug reports are accepted with this flag on. Then I don't see a problem :)

Comment (zeriong) [reply packages/core/src/types.ts]: Thanks for the feedback @snebjorn! That makes total sense.

I'll update the PR with the following changes:

1. **Rename** `input.validation` → `input.unsafeDisableValidationYolo` (inverted semantics — `true` to disable)
2. **Restore hard error as default** — when validation fails and the flag is not set, orval will throw as before
3. **Add a very noticeable warning** when the flag is enabled:
   - Banner-style warning at startup
   - Clear message that no bug reports are accepted with this flag on
4. When `unsafeDisableValidationYolo: true`, skip all validation (both `validateSpec` and `validateComponentKeys`) and continue generation

This keeps the safe default while giving users with non-standard specs (like FastAPI's `itemSchema`) an explicit escape hatch they can't accidentally stumble into.

Will push the update shortly!

Comment (melloware) [reply packages/core/src/types.ts]: I think @snebjorn  was kidding about the name?

**Comment by zeriong** [comment]
@snebjorn Review is welcome!

File: packages/core/src/types.ts (hunk 1 above)
Comment (snebjorn) [reply packages/core/src/types.ts]: yes, it was a joking example. I've seen options like this in the wild but can't recall any right now.

IMO the option name should indicate that it's "turn on at your own risk" and it might break at any point

Comment (zeriong) [reply packages/core/src/types.ts]: Yeah! I actually understood it! 😁

File: packages/core/src/types.ts [hunk 2]
```diff
@@ -326,6 +327,8 @@ export interface InputFiltersOptions {
 export interface InputOptions {
   target: string | string[] | Record<string, unknown> | OpenApiDocument;
   override?: OverrideInput;
+  /** Enable or disable OpenAPI spec validation. Default: true */
+  validation?: boolean;
```
Comment (snebjorn) [inline packages/core/src/types.ts:331]: IMO the option name should indicate that it's "turn on at your own risk" and it might break at any point.

Best I can come up with is `unsafeDisableValidation`, but feel free to play with this.

File: packages/orval/src/import-specs.ts [hunk 3]
```diff
@@ -41,11 +43,24 @@ async function resolveSpec(
...
+  if (validation) {
+    validateComponentKeys(dereferencedData);
+
+    const { valid, errors } = await validateSpec(dereferencedData);
+    if (!valid) {
+      throw new Error(
+        `OpenAPI spec validation failed:\n${JSON.stringify(errors, undefined, 2)}\n\n` +
+          `If your spec uses non-standard extensions and you want to skip validation,\n` +
+          `set input.validation to false in your orval config.\n` +
+          `Note: no bug reports are accepted with validation disabled.`,
```
Comment (snebjorn) [inline packages/orval/src/import-specs.ts:55]: I don't think we should advertise this.

File: bun.lock [hunk 4]
```diff
@@ -1758,15 +1760,15 @@
 
     "@swc/helpers": ["@swc/helpers@0.5.15", "", { "dependencies": { "tslib": "^2.8.0" } }, "sha512-JQ5TuMi45Owi4/BIMAJBoSQoOJu12oOk/gADqlcUL9JEdHB8vyjUSsxqeNXnmXHjYKMi2WcYtezGEEhqUI/E2g=="],
 
-    "@tanstack/angular-query-experimental": ["@tanstack/angular-query-experimental@5.90.25", "", { "dependencies": { "@tanstack/query-core": "5.90.20" }, "optionalDependencies": { "@tanstack/query-devtools": "5.93.0" }, "peerDependencies": { "@angular/common": ">=16.0.0", "@angular/core": ">=16.0.0" } }, "sha512-8MmtvEq83kRbwtt6NNbDAWPMOFHLxSmvhScFtdmBP/Xo5gSSzAf4JHcblQDHV/CgWIGKOp7eOa6aXDiVIK+kbw=="],
+    "@tanstack/angular-query-experimental": ["@tanstack/angular-query-experimental@5.90.16", "", { "dependencies": { "@tanstack/query-core": "5.90.12" }, "optionalDependencies": { "@tanstack/query-devtools": "5.91.1" }, "peerDependencies": { "@angular/common": ">=16.0.0", "@angular/core": ">=16.0.0" } }, "sha512-ezXyxuaSA6kpwUxwrxo5Tf3B7KL7mb7cxhLnun/RMlw6h3ZQJzl1cJgrvN97+C0AeHoucmK7RwhEoIY12gY7WA=="],
```
Comment (snebjorn) [inline bun.lock:1763]: seems some packages were downgraded, why?

**Review by snebjorn — CHANGES_REQUESTED** [review]
The docs also need to be updated

File: packages/core/src/types.ts (hunk 2 above)
Comment (zeriong) [reply packages/core/src/types.ts]: Agree. Renaming to unsafeDisableValidation and updating docs!

File: packages/orval/src/import-specs.ts (hunk 3 above)
Comment (zeriong) [reply packages/orval/src/import-specs.ts]: Ok, Thanks for reiview!

File: bun.lock (hunk 4 above)
Comment (zeriong) [reply bun.lock]: Good catch.
I pinned 5.90.16 in the catalog to match the sample's existing ^5.90.16, but the lockfile had already resolved to 5.90.25 before.

The pin caused the unintended downgrade.
I'll bump the catalog to the latest compatible version!

**Review by melloware — DISMISSED** [review]

**Review by snebjorn — APPROVED** [review]
