### PR TITLE
fix(msw): make sure to not double import value and type

### LINKED ISSUE #1798: Double import of enum in generated mock file
## What are the steps to reproduce this issue?

Use this schema:
```json
{
    "openapi": "3.0.1",
    "info": {
      "title": "Test",
      "version": "1.0"
    },
    "paths": {
      "/api/useradmin/organization/bankidusage": {
        "get": {
          "tags": [
            "UserAdmin"
          ],
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/BankIdUsage"
                  }
                }
              }
            }
          }
        }
      },
      "/api/useradmin/users/{userId}": {
        "get": {
          "tags": [
            "UserAdmin"
          ],
          "parameters": [
            {
              "name": "userId",
              "in": "path",
              "required": true,
              "schema": {
                "type": "string",
                "format": "uuid"
              }
            }
          ],
          "responses": {
            "200": {
              "description": "OK",
              "content": {
                "application/json": {
                  "schema": {
                    "$ref": "#/components/schemas/UserAdminDto"
                  }
                }
              }
            }
          }
        }
      }
    },
    "components": {
      "schemas": {
        "BankIdUsage": {
          "enum": [
            "Allow",
            "Deny",
            "Force"
          ],
          "type": "string",
          "x-enumNames": [
            "Allow",
            "Deny",
            "Force"
          ]
        },
        "UserAdminDto": {
          "required": [
            "bankIdUsage"
          ],
          "type": "object",
          "properties": {
            "bankIdUsage": {
              "allOf": [
                {
                  "$ref": "#/components/schemas/BankIdUsage"
                }
              ],
              "x-enumNames": [
                "Allow",
                "Deny",
                "Force"
              ]
            }
          },
          "additionalProperties": false
        }
      }
    }
  }
```
and generate with mocks enabled.

## What happens?

This is the resulting imports:
image

## What were you expecting to happen?

Only the value import should happen if both the type and value is needed:
image

## Any logs, error output, etc?

`Duplicate identifier 'BankIdUsage'.`

## Any other comments?

PR coming

## What versions are you using?

Latest orval

### PR DESCRIPTION
**Pull request by AllieJonsson**
## Status

**READY**

## Description

Fixes #1798 

## Todos

- [x] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Follow steps in linked issue

### CODE REVIEW

File: packages/core/src/generators/imports.ts [hunk 1]
```diff
@@ -234,6 +234,11 @@ export const addDependency = ({
 
       if (types) {
         if (values) {
+          for (let i = types.length - 1; i >= 0; i--) {
```
Comment (anymaniax) [inline packages/core/src/generators/imports.ts]: instead of using splice would you be ok to recreate and array without the duplicated type? If we have a side effect from this it could be difficult to debug otherwise.

**Review by melloware — DISMISSED** [review]

File: packages/core/src/generators/imports.ts [hunk 2]
```diff
@@ -234,6 +234,7 @@ export const addDependency = ({
 
       if (types) {
         if (values) {
+          types = types.filter((t) => !values.some((v) => v.name === t.name));
```
Comment (soartec-lab) [inline packages/core/src/generators/imports.ts]: You should avoid overriding variable names whenever possible, so give them different names 👍 

```suggestion
          uniqueTypes = types.filter((t) => !values.some((v) => v.name === t.name));
```

**Review by soartec-lab — CHANGES_REQUESTED** [review]
@AllieJonsson 
Thank you for the correction. I added a small change request in the comments..

**Review by soartec-lab — APPROVED** [review]
Thanks!
