### PR TITLE
fix(fetch): parse response body based on content-type instead of always JSON.parse

### LINKED ISSUE #3088: fetch: generated code always parses the body as JSON, even though it may be plain text.
### Description

https://github.com/orval-labs/orval/blob/43146fdfee6c1afa2bb99ba5779b43470a1a8746/packages/fetch/src/index.ts#L395-L411

It seems the fetch client currently special-cases only NDJSON responses. For non-NDJSON responses, it always does `await res.text()` followed by `JSON.parse(...)`, without considering response content-type such as text/plain, which leads to runtime errors.

### Configuration (orval.config)

n/a

### Environment

n/a

### Expected behavior

_No response_

### Actual behavior

_No response_

### OpenAPI document (minimal, if applicable)

```yaml
"responses": {
  "200": {
    "description": "",
    "content": {
      "application/json": {
        "schema": {
          ...
        }
      }
    }
  },
  "429": {
    "description": "Too Many Requests",
    "content": {
      "text/plain": {
        "schema": {
          "type": "string"
        }
      }
    }
  }
}
```

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by zeriong**
## Summary

- The generated fetch client always called `JSON.parse(body)` regardless of the response Content-Type, causing runtime errors for non-JSON responses
- For example, a `429 Too Many Requests` returning `text/plain` would throw a SyntaxError because `JSON.parse("Too Many Requests")` is invalid
- Binary responses (`image/png`, `application/octet-stream`, etc.) were also broken since `res.text()` corrupts binary data

## Changes

- `packages/fetch/src/index.ts`
  - Added `const isBlob = response.isBlob` — previously computed in core but never used in the fetch client
  - Non-blob responses: added `const contentType = res.headers.get('content-type') ?? ''` and replaced `JSON.parse(body)` with `contentType.includes('json') ? JSON.parse(body) : body`
  - Blob responses: generate a separate code path that uses `await res.blob()` for success and `await res.text()` with content-type detection for error bodies (so error info is still parseable as JSON or text)
  - `throwOnErrorImplementation` updated for all three response categories (NdJson / blob / regular)
- `tests/specifications/mixed-content-responses.yaml` — new test spec covering: JSON+text/plain mixed status codes (exact issue scenario), text/plain only, and binary image/png
- `tests/configs/fetch.config.ts` — two new test configs for the new spec (default and forceSuccessResponse)
- All affected snapshots updated (fetch, react-query, vue-query, swr, mcp, default clients all share `generateRequestFunction` from `@orval/fetch`)

## Test plan

- [x] New generated output for `getData` endpoint (JSON 200 + text/plain 429): uses `contentType.includes('json')` guard — correct for both status codes
- [x] New generated output for `getText` endpoint (text/plain 200): returns body as-is, no JSON.parse
- [x] New generated output for `getImage` endpoint (image/png 200): uses `res.blob()` for success, `res.text()` for error
- [x] `bun run test:snapshots` — 3556 tests pass, 0 failures
- [x] `bun vitest run` — 2215 pass (3 pre-existing failures in resolve-version.test.ts unrelated)
- [x] `bun run lint` — no errors
- [x] `bun run typecheck` — no errors
- [x] `bun run build` — success

Closes #3088

## Summary by CodeRabbit

* **New Features**
  * Clients now detect response Content-Type and handle JSON, text, and binary/blob success payloads, including new generated clients for mixed-content scenarios.

* **Bug Fixes**
  * Response parsing now respects Content-Type: JSON parsed only for JSON responses; non-JSON bodies return raw text. No-body statuses (204/205/304) still yield empty payloads.

* **Chores**
  * Updated generated snapshots, tests, fixtures, and configs to reflect content-type-aware response handling.

### CODE REVIEW

**Comment by melloware** [comment]
@soartec-lab please review

File: packages/fetch/src/index.ts [hunk 1]
```diff
@@ -417,15 +441,18 @@ ${override.fetch.forceSuccessResponse && hasSuccess ? '' : `export type ${respon
...
+      ? blobFetchResponseImplementation
+      : `const res = await ${fetchFnCall}(${fetchFnOptions})
 
+  const contentType = res.headers.get('content-type') ?? '';
   const body = [204, 205, 304].includes(res.status) ? null : await res.text();
   ${override.fetch.forceSuccessResponse ? throwOnErrorImplementation : ''}
   ${
     isValidateResponse
-      ? `const parsedBody = body ? JSON.parse(body${reviver}) : {}
+      ? `const parsedBody = body ? (contentType.includes('json') ? JSON.parse(body${reviver}) : body) : {}
```
Comment (soartec-lab) [inline packages/fetch/src/index.ts]: How about using the `content-type` defined in `openapi` for this definition? And if `content-type` is not specified, the default value can remain the same as before, assuming JSON.

Comment (soartec-lab) [reply packages/fetch/src/index.ts]: Ah, so there are cases where the content types are mixed and determined dynamically at runtime.

Comment (soartec-lab) [reply packages/fetch/src/index.ts]: Checking `contentType.includes('json')` is only necessary when there's a mix of formats, right?

Comment (zeriong) [reply packages/fetch/src/index.ts]: @soartec-lab 
Yes, exactly. For operations where OpenAPI spec declares a single unambiguous content type 
(e.g., only `application/json`), we could use the spec-defined type at generation time and 
skip the runtime check.

The runtime check is necessary only when the same operation has mixed content types across 
different status codes (e.g., 200 → application/json, 429 → text/plain).

If you prefer, I can change the approach to:
1. At generation time, check if the operation has mixed content types
2. If all responses share the same type → use it directly (no runtime header check)
3. If mixed → emit the runtime `content-type` header check

Would that be the direction you'd like?

Comment (soartec-lab) [reply packages/fetch/src/index.ts]: @zeriong Yes, that would be good 👍

**Review by melloware — DISMISSED** [review]

File: packages/fetch/src/index.ts (hunk 1 above)
Comment (zeriong) [reply packages/fetch/src/index.ts]: @soartec-lab It's improved! Please check it out 👍🏻

File: samples/react-app-with-swr/fetch-client/__snapshots__/endpoints/swaggerPetstore.ts [hunk 2]
```diff
@@ -171,7 +171,7 @@ export const showPetById = async (
 
   const body = [204, 205, 304].includes(res.status) ? null : await res.text();
 
-  const data: Pet = body ? JSON.parse(body) : {};
+  const data: Pet = body !== null ? JSON.parse(body) : {};
```
Comment (soartec-lab) [inline samples/react-app-with-swr/fetch-client/__snapshots__/endpoints/swaggerPetstore.ts]: This is an unexpected change. It will now throw an exception when it's `undefined`.

Comment (zeriong) [reply samples/react-app-with-swr/fetch-client/__snapshots__/endpoints/swaggerPetstore.ts]: OMG... That is my mistake, Thanks!

**Comment by zeriong** [comment]
@soartec-lab Now is done! Please check this one~!

**Review by melloware — APPROVED** [review]

**Review by melloware — APPROVED** [review]

**Comment by soartec-lab** [comment]
@zeriong @melloware 

I'm sorry, but this is still an unresolved issue so I'm reverting it.

File: tests/__snapshots__/default/index-mock-file/health/health.ts [hunk 3]
```diff
@@ -86,7 +86,7 @@ export const healthCheck = async (
 
   const body = [204, 205, 304].includes(res.status) ? null : await res.text();
 
-  const data: healthCheckResponse['data'] = body ? JSON.parse(body) : {};
+  const data: healthCheckResponse['data'] = body !== null ? body : '';
```
Comment (soartec-lab) [inline tests/__snapshots__/default/index-mock-file/health/health.ts:89]: Why is this change necessary? Does this change relate to the purpose of this project?

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts [hunk 4]
```diff
@@ -162,10 +169,17 @@ export const createPets = async (
     body: JSON.stringify(createPetsBody),
   });
 
+  const contentType = (res.headers.get('content-type') ?? '').toLowerCase();
```
Comment (soartec-lab) [inline tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:172]: What is the purpose of this `toLowerCase`? Why can't I just use the default string?

```suggestion
  const contentType = (res.headers.get('content-type') ?? '');
```

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts [hunk 5]
```diff
@@ -162,10 +169,17 @@ export const createPets = async (
...
   const body = [204, 205, 304].includes(res.status) ? null : await res.text();
 
-  const parsedBody = body ? JSON.parse(body) : {};
-  const data = Pet.parse(parsedBody);
+  const parsedBody = body
```
Comment (soartec-lab) [inline tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:175]: What happens if there are three or more content types?

File: tests/specifications/mixed-content-responses.yaml [hunk 6]
```diff
@@ -0,0 +1,73 @@
...
+      operationId: getImage
+      responses:
+        '200':
+          description: Binary image response
+          content:
+            image/png:
+              schema:
+                type: string
+                format: binary
+  /mixed-success:
```
Comment (soartec-lab) [inline tests/specifications/mixed-content-responses.yaml:52]: Isn't this test case from the same perspective as getData? If so, I want to keep the tests to a minimum, so one case is sufficient.

**Review by soartec-lab — COMMENTED** [review]
Automatic reverting was not possible, so please revert it manually. There are still several fundamental questions that need to be addressed before we can even review this PR before merging it.

**Comment by melloware** [comment]
don't revert just submit a new PR fixing the issues

**Comment by zeriong** [comment]
@melloware @soartec-lab 

I'm so sorry, the code mixed with the previous content went up the same way, and the PR was accepted. I'll open a new PR referring to this PR as soon as possible! 🥹

File: tests/__snapshots__/fetch/mixed-content-responses/endpoints.ts [hunk 7]
```diff
@@ -0,0 +1,157 @@
...
+  const res = await fetch(getGetDataUrl(), {
+    ...options,
+    method: 'GET',
+  });
+
+  const body = [204, 205, 304].includes(res.status) ? null : await res.text();
+
+  const data: getDataResponse['data'] = body ? JSON.parse(body) : {};
+  return { data, status: res.status, headers: res.headers } as getDataResponse;
+};
```
Comment (Huliiiiii) [inline tests/__snapshots__/fetch/mixed-content-responses/endpoints.ts:48]: This vibe pr did not solve my issue. 
Given the following input (tests/specifications/mixed-content-responses.yaml):
```
/data:
  get:
    summary: Returns JSON on success, plain text on rate limit
    operationId: getData
    responses:
      '200':
        description: Successful response
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: integer
                name:
                  type: string
      '429':
        description: Too Many Requests
        content:
          text/plain:
            schema:
              type: string
```
This will still parse text as json.

File: packages/fetch/src/index.ts [hunk 8]
```diff
@@ -398,16 +431,66 @@ ${override.fetch.forceSuccessResponse && hasSuccess ? '' : `export type ${respon
...
+    const data ${hasError ? `: ${errorName}${override.fetch.includeHttpResponseReturnType ? `['data']` : ''}` : ''} = ${throwOnErrorDataExpression}
     err.info = data;
     err.status = ${isNdJson ? 'stream' : 'res'}.status;
     throw err;
   }`;
   const fetchFnCall =
     useRuntimeFetcher && isRequestOptions ? '(fetchFn ?? fetch)' : 'fetch';
+  const blobFetchResponseImplementation = `const res = await ${fetchFnCall}(${fetchFnOptions})
+
+  ${override.fetch.forceSuccessResponse ? throwOnErrorImplementation : ''}
```
Comment (Huliiiiii) [inline packages/fetch/src/index.ts:485]: That's because the new logic was added to throwOnErrorImplementation, which only gets executed when forceSuccessResponse is enabled.

File: tests/__snapshots__/fetch/mixed-content-responses/endpoints.ts (hunk 7 above)
Comment (zeriong) [reply tests/__snapshots__/fetch/mixed-content-responses/endpoints.ts:48]: I'm sure the source code went up wrong. Thank you for checking! I'll refer to it and include it in the new pr!

File: packages/fetch/src/index.ts (hunk 8 above)
Comment (zeriong) [reply packages/fetch/src/index.ts:485]: I'll refer to it and reflect it on the new pr!

File: tests/__snapshots__/default/index-mock-file/health/health.ts (hunk 3 above)
Comment (zeriong) [reply tests/__snapshots__/default/index-mock-file/health/health.ts:89]: This `health` endpoint returns plain text.
Before #3222, the generated client ran `JSON.parse(body)` on it and threw at runtime. After #3222, we branch on `Content-Type` and `body !== null ? body : ''` keeps the distinction between "no-content (204/205/304) → `null`" and "empty text body → `''`" explicit. CodeRabbit flagged the same collapse-into-one pattern across many snapshots; #3261 reuses this exact shape.

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts (hunk 4 above)
Comment (zeriong) [reply tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:172]: Per RFC 9110 §8.3.1, media type tokens are case-insensitive — servers do send `Application/JSON`. Without `.toLowerCase()`, `includes('json')` misses those and we hand parsed JSON back as raw text. Normalizing once up front keeps every downstream check a plain `.includes('json')`, which I think reads more clearly than a case-insensitive regex at every call site. CodeRabbit raised the same point on ~12 snapshots in #3222. Happy to add a one-line comment citing the RFC if that helps.

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts (hunk 5 above)
Comment (zeriong) [reply tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:175]: The dispatch is intentionally two-branch — "is this body JSON?". That holds for 3+ content types too: JSON goes to `JSON.parse`, anything else textual stays as raw text, and binary types (`image/png`, `application/octet-stream`) are detected at generation time and emit a separate `res.blob()` branch instead. `tests/specifications/mixed-content-responses.yaml` exercises exactly this three-type shape (`/data`, `/text`, `/image`). #3261 is the piece that closes the last gap — it extends the "is this mixed?" detection to error content types too.

File: tests/specifications/mixed-content-responses.yaml (hunk 6 above)
Comment (zeriong) [reply tests/specifications/mixed-content-responses.yaml:52]: Agreed — same runtime dispatch as `/data`, so one case is enough. Quick context: `/mixed-success` was the only fixture that actually triggered the mixed-detection under the default `forceSuccessResponse: false`, because #3222's detector only looked at 2xx content types. #3261 extends that detector to error content types, so `/data` now covers both shapes on its own. Happy to drop `/mixed-success` in a follow-up.

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts (hunk 4 above)
Comment (soartec-lab) [reply tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:172]: I understand perfectly.

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts (hunk 5 above)
Comment (soartec-lab) [reply tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:175]: @zeriong 
Specifically, can you handle cases like these?

```
'200':
  description: Binary image response
  content:
    image/png:
      schema:
        type: string
        format: binary

'422':
  content:
    application/json:
      schema:
        type: object
        properties:
          errorCode:
            type: integer
          message:
            type: string
'429':
  description: Too Many Requests
  content:
    text/plain:
      schema:
        type: string
```

File: tests/specifications/mixed-content-responses.yaml (hunk 6 above)
Comment (soartec-lab) [reply tests/specifications/mixed-content-responses.yaml:52]: @zeriong 

In that case, please delete one of them.

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts (hunk 5 above)
Comment (zeriong) [reply tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:175]: @soartec-lab Thanks for the concrete spec. I've already opened a follow-up PR (#3261, branch `fix/fetch-mixed-content-error-parsing-3088`) that extends the parse-strategy detection to error content types when `forceSuccessResponse` is false. Traced the generator end-to-end against that branch for your exact case:

**Handled — `forceSuccessResponse: true`**: `response.isBlob` is `true` (success has `image/png`), so `blobFetchResponseImplementation` is selected ([packages/fetch/src/index.ts L491-L501](https://github.com/zeriong/orval/blob/d7bad64662b66ca838743a541242a98c34b346f4/packages/fetch/src/index.ts#L491-L501)). `throwOnErrorImplementation` is emitted ([L493](https://github.com/zeriong/orval/blob/d7bad64662b66ca838743a541242a98c34b346f4/packages/fetch/src/index.ts#L493)); since `errorContentTypes = ['application/json', 'text/plain']`, `hasMixedErrorContentTypes` is `true`, so the inner declarations emit `errorBody = await res.text()` plus `errorContentType` ([L470-L471](https://github.com/zeriong/orval/blob/d7bad64662b66ca838743a541242a98c34b346f4/packages/fetch/src/index.ts#L470-L471)) and the data expression resolves to `errorBody ? (errorContentType.includes('json') ? JSON.parse(errorBody) : errorBody) : {}` ([L446-L450, L460-L461](https://github.com/zeriong/orval/blob/d7bad64662b66ca838743a541242a98c34b346f4/packages/fetch/src/index.ts#L446-L461)). Result: `200` → Blob, `422` → parsed JSON, `429` → string. ✓

**Not yet handled — default `forceSuccessResponse: false`**: same blob path is taken (still `isBlob` true), but `throwOnErrorImplementation` is *not* emitted ([L493](https://github.com/zeriong/orval/blob/d7bad64662b66ca838743a541242a98c34b346f4/packages/fetch/src/index.ts#L493)). Line 494 unconditionally calls `await res.blob()` for every non-204 status, then casts to the response type — so `422`/`429` bodies come back as raw `Blob` even though the generated TypeScript types declare them as the parsed JSON/string shapes. No `JSON.parse` exception (the literal #3088 SyntaxError is gone), but the runtime value diverges from the declared type. This is a pre-existing limitation of the blob branch (predates #3222), not a regression.

Plan I'd like to confirm with you before pushing:
1. Add this exact spec (binary 200 + JSON 422 + text 429) to `mixed-content-responses.yaml` so the `forceSuccessResponse: true` behavior is locked in by snapshot.
2. Extend the default-mode blob path in #3261 to dispatch on `Content-Type` for non-2xx statuses, reusing the `errorContentType` mechanism that already exists in the throw-on-error path.

Does this direction work for you? If yes, I'll push the changes onto #3261 (or open a fresh PR if you'd prefer that for review hygiene — let me know).

File: tests/specifications/mixed-content-responses.yaml (hunk 6 above)
Comment (zeriong) [reply tests/specifications/mixed-content-responses.yaml:52]: @soartec-lab 
Agreed. I'm tracking this on the follow-up PR (#3261, branch `fix/fetch-mixed-content-error-parsing-3088`). Verified by re-tracing on that branch: for `getMixedSuccess` (200 `application/json` + 206 `text/plain`), `parseTimeContentTypes` ends up `['application/json', 'text/plain']` and `hasMixedSuccessContentTypes` is `true`, hitting the same template branch ([packages/fetch/src/index.ts L528-L529](https://github.com/zeriong/orval/blob/d7bad64662b66ca838743a541242a98c34b346f4/packages/fetch/src/index.ts#L528-L529)) as `getData` (200 `application/json` + 429 `text/plain`). The two snapshots produce identical parse logic, so `/mixed-success` is redundant.

Plan I'd like to confirm with you before pushing:
1. Remove `/mixed-success` from `mixed-content-responses.yaml`.
2. Update the affected snapshots and `tests/configs/fetch.config.ts` accordingly.

Does this direction work? If yes, I'll push onto #3261 (or split into a fresh PR if you prefer that for review hygiene — let me know).

Comment (soartec-lab) [reply tests/specifications/mixed-content-responses.yaml:52]: @zeriong 
Yes!

File: tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts (hunk 5 above)
Comment (soartec-lab) [reply tests/__snapshots__/fetch/zod-schema-response-split/endpoints.ts:175]: @zeriong 
Could you please write the source code for the output you expect here?
Of course, please add tests. However, if you do, please extend the two mixed tests, rather than adding new test cases.
