### PR TITLE
fix(mcp): avoid fake Body imports for inline request bodie

### LINKED ISSUE #2722: orval/mcp generator  wrong Body imports when body is inline/primitive
### Summary

  In `mcp` mode the generator adds `${operationanme}Body` imports even when the request body is inline/primitive (no component), so the generated handlers import non-existent  types.

  Repro:
  - Check the reproduction repo: [link](https://github.com/froggy1014/mcp-gen-repor)
  - Spec includes an inline array body (e.g., POST /domains/available/bulk with body: string[]) and a component-backed body (POST /domains/purchase -> #/components/schemas/DomainPurchase).
  - Run `orval --config ...` with `client: "mcp"`, `mode: "single"`, `schemas` set.
  - Generated `handlers.ts` tries to import `AvailableBulkBody` from `./http-schemas`, but that type isn’t generated.

```yaml
  paths:
    /domains/available/bulk:
      post:
        operationId: availableBulk
        requestBody:
          required: true
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
    /domains/purchase:
      post:
        operationId: purchase
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainPurchase'
  components:
    schemas:
      DomainPurchase:
        type: object
        properties:
          domain:
            type: string
```

```ts
import {
  AvailableBulkBody,  // Module '"./http-schemas"' has no exported member 'AvailableBulkBody'.
  PurchaseBody, // Module '"./http-schemas"' has no exported member 'PurchaseBody'
  ContactsValidateBody // Module '"./http-schemas"' has no exported member 'ContactsValidateBody'
} from './http-schemas';
```

  If this is indeed a bug, I’m happy to open a PR with the fix.

### PR DESCRIPTION
**Pull request by froggy1014**
## Summary
  
  - fix mcp generator so inline/primitive request bodies don’t force `${PascalOperationName}Body` imports
  - use `body.imports[0]?.name` when present; otherwise skip
  adding a Body import
  
  Fixes #2722

## Details
  
  - updated `packages/mcp/src/index.ts` to prefer explicit body import names and drop the definition-based Body fallback that created non-existent imports (e.g., `{OperationName}Body` for inline string[] bodies)

## Testing
  
  -  please use this [re-production repo](https://github.com/froggy1014/mcp-gen-reproduction)

### CODE REVIEW

File: packages/mcp/src/index.ts [hunk 1]
```diff
@@ -61,8 +61,8 @@ export const getMcpHeader: ClientHeaderBuilder = ({ verbOptions, output }) => {
         imports.push(`${pascalOperationName}Params`);
       }
 
-      if (verbOption.body.definition) {
-        imports.push(`${pascalOperationName}Body`);
+      if (verbOption.body.imports[0]?.name) {
+        imports.push(verbOption.body.imports[0]?.name);
```
Comment (melloware) [inline packages/mcp/src/index.ts:65]: Does this still need to pascal wrap it?

**Review by melloware — CHANGES_REQUESTED** [review]

**Comment by froggy1014** [comment]
@melloware 

can we set angular run-time packages moves in to yarnrc.yaml ?

**Comment by melloware** [comment]
I rebased your branch.  that is a question for @snebjorn he helped refactor all this to Yarn workspaces.

File: packages/mcp/src/index.ts (hunk 1 above)
Comment (froggy1014) [reply packages/mcp/src/index.ts:65]: > Does this still need to pascal wrap it?

@melloware

The body type name is already PascalCased upstream in the schema pipeline.

getResReqTypes/getBody builds body.imports with the PascalCase schema name (from the $ref or inline schema).

```ts
// getResReqTypes (excerpt)
  if (isReference(res)) {
    const {
      schema: bodySchema,
      // resolveRef returns the schema name (PascalCased)
      imports: [{ name, schemaName }],
    } = resolveRef(res, context);
    // getRefInfo() : pascal was mad e-> getSchema() -> resolveRef()

    // name/schemaName are pushed into imports
    return [
      {
        value: name,
        imports: [{ name, schemaName }],
        // ...
      },
    ];
  }

  if (res.content) {
    const contents = Object.entries(res.content).map(
      ([contentType, mediaType], index, arr) => {
        // inline schemas also get PascalCase names
        let propName = key ? pascal(name) + pascal(key) : undefined;
        if (propName && arr.length > 1) {
          propName = propName + pascal(getNumberWord(index + 1));
        }
        // ...
      },
    );
    // ...
  }
  
  ```
  
  
When we read verbOption.body.imports[0].name we’re getting that same PascalCase type, so an extra pascalOperationName + 'Body' wrap isn’t needed.

**Comment by froggy1014** [comment]
> I rebased your branch. that is a question for @snebjorn he helped refactor all this to Yarn workspaces.

@melloware 

- https://github.com/orval-labs/orval/pull/2726

  Could you please assign this PR to @snebjorn ? thanksss

**Comment by melloware** [comment]
I accepted it. That was kick ass I will have him look it over!
