### PR TITLE
fix(query): prioritize query over mutation for non-GET operations in generateQueryHook

### LINKED ISSUE #2025: Duplicate non-infinite hooks generated when infinite query enabled for POST endpoints
I have produced an example project/repo showcasing this bug [here](https://github.com/Edward-Upton/orval-duplicate-hook-bug), where there are duplicate hooks being generated with the same signature in [`src/index.ts`](https://github.com/Edward-Upton/orval-duplicate-hook-bug/blob/main/src/index.ts#L263).

The specific issue seems to appear when you have a POST operation, e.g.:
```
/items:
    post:
      operationId: searchItems
      summary: Search for items with pagination
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SearchRequest"
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedItemsResponse"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
```

and then enable infinite query generation on it:

```
      override: {
        operations: {
          searchItems: {
            query: {
              useQuery: true,
              useInfinite: true,
              useInfiniteQueryParam: "cursor",
            },
          },
        },
      },
```

which then results in multiple of the same hooks for the normal (non-infinite-query) hook being generated

Some other things I've tried are:
- Removing the `useQuery: true` option --> doesn't change the generated code (i.e. still fails).
- Using a top-level `useInfinite: true` (not operation specific) --> this doesn't generate an infinite query hook for POSTs (potentially another bug).

Note that this does not fail if the endpoint is a GET endpoint, only for POSTs (my example repo includes a GET endpoint to showcase this).

### PR DESCRIPTION
**Pull request by Edward-Upton**
## Status

**READY**

Fix #2025

## Description

Ensures that only one of the queries or mutations are generated, giving priority to queries.

## Todos

- [ ] Tests
- [ ] Documentation
- [ ] Changelog Entry (unreleased)

## Steps to Test or Reproduce

Run on the test repo that shows the bug in action

https://github.com/Edward-Upton/orval-duplicate-hook-bug

### CODE REVIEW

**Comment by melloware** [comment]
Running the tests now!

File: packages/query/src/index.ts [hunk 1]
```diff
@@ -1129,6 +1129,17 @@ const generateQueryHook = async (
...
   }
 
+  // For non-GET operations, only register query OR mutation hooks, not both
+  let isMutation = verb !== Verbs.GET && override.query.useMutation;
+  if (operationQueryOptions?.useMutation !== undefined) {
+    isMutation = operationQueryOptions.useMutation;
+  }
+
+  // If both query and mutation are true for a non-GET operation, prioritize query
+  if (verb !== Verbs.GET && isQuery && isMutation) {
```
Comment (soartec-lab) [inline packages/query/src/index.ts]: If `isQuery` is true, we don't need to consider `isMutation`, right?

```suggestion
  if (verb !== Verbs.GET && isQuery) {
```

File: packages/query/src/index.ts [hunk 2]
```diff
@@ -1129,6 +1129,17 @@ const generateQueryHook = async (
     isQuery = operationQueryOptions.useSuspenseQuery;
   }
 
+  // For non-GET operations, only register query OR mutation hooks, not both
+  let isMutation = verb !== Verbs.GET && override.query.useMutation;
```
Comment (soartec-lab) [inline packages/query/src/index.ts]: The verb is checked last, after all options have been checked, so it is best to leave this step for last.

```suggestion
  let isMutation = operationQueryOptions.useMutation || override.query.useMutation;
  
  if (verb !== Verbs.GET && isQuery) {
      isMutation = false;
  }
```

**Review by soartec-lab — COMMENTED** [review]
@Edward-Upton 

Thank you for the nice correction. I made a comment.
I think it needs to be reflected in the documentation, but I'll think about it for a bit.

**Comment by Edward-Upton** [comment]
I have resolved the comments, thanks for the review 😄

**Review by soartec-lab — COMMENTED** [review]
@Edward-Upton 
Thanks!
I thought about documentation. Please clarify the specifications in the guide for the following options.

1. Only valid when the verbs of the two mutations are not get and not query
2. Prioritize `output.mutation` over `output.orverride.mutation`

- https://orval.dev/reference/configuration/output#usemutation
- https://orval.dev/reference/configuration/output#usemutation

Could you update docs ?

**Review by soartec-lab — APPROVED** [review]
It's good !

**Comment by AllieJonsson** [comment]
It seems like this change broke samples, where we now get multiple implementation of the hooks

**Comment by soartec-lab** [comment]
@AllieJonsson 
Oh, will that be fixed by just re-running orval in samples?

**Comment by AllieJonsson** [comment]
@soartec-lab No, I tried generating samples in #2035 but the issue persists

**Comment by AllieJonsson** [comment]
@soartec-lab isn't it weird that we don't see if samples break in the PR, but in the following PRs? That must mean that we don't correctly build/test samples?
