### PR TITLE
fix(fetch): make sure responseDataType is not empty

### LINKED ISSUE #1826: Response type missing when using Fetch with empty schema
## What are the steps to reproduce this issue?

1. Use the following schema
```yaml
openapi: 3.0.1
info:
  title: Test
  version: v1.0
paths:
  /test:
    get:
      description: Test
      operationId: test
      responses:
        200:
          description: Test
          content:
            application/json:
              schema:
                example: {}
```
2. Generate with `client: fetch`

## What happens?
```ts
export type testResponse = {
  data: ;
  status: number;
  headers: Headers;
}
```

## What were you expecting to happen?
```ts
export type testResponse = {
  data: unkown;
  status: number;
  headers: Headers;
}
```

### PR DESCRIPTION
**Pull request by AllieJonsson**
## Status

**READY**

## Description

Fixes #1826

### CODE REVIEW

**Review by melloware — DISMISSED** [review]

**Comment by soartec-lab** [comment]
I will check later 👍

File: packages/fetch/src/index.ts [hunk 1]
```diff
@@ -114,10 +114,8 @@ ${
     operationName,
   );
 
-  const responseDataType =
-    response.definition.success || response.definition.errors
-      ? `${response.definition.success !== 'unknown' ? response.definition.success : ''}${response.definition.success !== 'unknown' && response.definition.errors !== 'unknown' ? ' | ' : ''}${response.definition.errors !== 'unknown' ? response.definition.errors : ''}`
-      : 'unknown';
+  let responseDataType = `${response.definition.success !== 'unknown' ? response.definition.success : ''}${response.definition.success !== 'unknown' && response.definition.errors !== 'unknown' ? ' | ' : ''}${response.definition.errors !== 'unknown' ? response.definition.errors : ''}`;
+  if (!responseDataType) responseDataType = 'unknown';
```
Comment (soartec-lab) [inline packages/fetch/src/index.ts]: It seems my changes were too complicated. This caused me to hit a bug 🥲 
I would like to simplify string generation and use immutable variables, so this is a refactoring suggestion.

```suggestion
  const responseDataSuccessType = response.definition.success !== 'unknown' ? response.definition.success : ''
  const responseDataTypeDelimiter = response.definition.success !== 'unknown' && response.definition.errors !== 'unknown' ? ' | ' : ''
  const responseDataErrorsType = response.definition.errors !== 'unknown' ? response.definition.errors : ''
  const responseDataType = responseDataSuccessType || responseDataErrorsType ? `${responseDataSuccessType}${responseDataTypeDelimiter}${responseDataErrorsType}` : 'unknown'
```

**Review by soartec-lab — CHANGES_REQUESTED** [review]
@AllieJonsson 
Thanks for handling this. And I added one suggestion.

**Review by soartec-lab — APPROVED** [review]
Thanks!
